name: iOS Build (Simulator)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build FoodDiaryTwo for iOS Simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Show versions
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Build (iphonesimulator)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p build_logs
          # Build target directly (no need for shared scheme)
          xcodebuild \
            -project "FoodDiaryTwo/FoodDiaryTwo.xcodeproj" \
            -target "FoodDiaryTwo" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            clean build \
            | tee build_logs/xcodebuild.log

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build_logs/


